install:
- bundle install
script:
- bundle exec rake deploy
env:
  matrix:
    secure: XCLjUFgrNwFWR1xMNCw2evtE1vSGQuP3hSE5vVY2e5rKAbAItV/GrScUvPpnZifDr7i8DvN5qoB1uJIYqP7j4NrJRSEzfiwEWst+H20cEj6+4eobwdPqMNPMYFeIegvT/Zd4smzrkVfXVrhXX1VkT85yKnqob3Sc6puFKDT7z4hpt+gf/jCr2KB7UOE7GdtSJznoQ+lAzuuDTBK4QYvRXmwa/RDvQ8YLVN/JkbigkRhW0JtkMYMAPlIPNW/Cfv77iPecqbsuYU3VxciMdgbLC3F4jX+yDtIpC6cJKh0TttNeR5WI8N/wGSDmepGMd7bYTdj1ohM+KttzyR62spf+56YACu2mForGp53c2qbBR/0VnxvHMWQmHopJsqp/9Z99rrDdv3qKtREVLJgzOH498am6DUZQFvGqYd0ZgAjGGIejbtFhNd8HDjJvJukI3e/Q1KhwRCHmFTB9+JSrwB0TcT98pMZ7JOZ9hf2K+YI/hPKFWFCM5l/67Afssu4W15oqoP+SDUyoZQQjR0JMdZ7D4eZtcs3gNCkicOxWV2IWblCbk4CRYhIQ/rn8L+tnwcz2k+njBw1X8NyCSrPVK1kIk2T1jUA98oE0av9Y1h3L0YNlqYv7K3DOsV4AgtJsOBVofvqtn8i2Sn7pGS1ObCdZMM8bWhCkRNTgPbKbX1kBLIc=
